name: ci
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Build
        run: go build .
  
      - uses: actions/upload-artifact@v3
        with:
          name: discordo_${{ runner.os }}_${{ runner.arch }}
          path: |
            discordo
